version: '3'

services:
  
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: sqlsql
      POSTGRES_USER: postgres
      POSTGRES_DB: my_db
    expose:
      - 5432
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - backend
  api:
    build:
      context: ./api
      dockerfile: Dockerfile-api
    command: yarn start
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
      - /app/node_modules
    links:
      - db
    depends_on:
      - db
    networks:
      - backend
  web:
    build:
      context: ./web
      dockerfile: Dockerfile-web
    volumes:
      - ./web:/web
    command: yarn start
    ports:
      - "3000:3000"
volumes:
  db-data:
networks:
  backend: