version: '3'

services:
  
  db:
    image: postgres
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile-api
    command: yarn start
    ports:
      - "8000:8000"
    volumes:
      - /api/app
    environment:
      - VIRTUAL_HOST=adamcordeiro.dev
    links:
      - db
  web:
    build:
      context: ./web
      dockerfile: Dockerfile-web
    volumes:
      - /web/app
    command: yarn start
    ports:
      - "3000:3000"
volumes:
  db-data:



  # build: ./result
  #   command: nodemon server.js
  #   volumes:
  #     - ./result:/app