version: '3'

services:
  
  db:
    image: postgres
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile-api
    command: yarn start
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
      - /app/node_modules
    links:
      - db
  web:
    build:
      context: ./web
      dockerfile: Dockerfile-web
    volumes:
      - ./web:/web
    command: yarn start
    ports:
      - "3000:3000"
volumes:
  db-data:
