version: '3'

services:
  
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: sqlsql
      POSTGRES_USER: postgres
      POSTGRES_DB: my_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - backend
  api:
    build:
      context: ./api
      dockerfile: Dockerfile-api
    command: yarn start
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
      - /app/node_modules
    depends_on:
      - db
    networks:
      - backend
  web:
    build:
      context: ./web
      dockerfile: Dockerfile-web
    volumes:
      - ./web:/web
      - /app/node_modules
    command: yarn start
    ports:
      - "3000:3000"
volumes:
  db-data:
networks:
  backend: